### PR TITLE
Fix Package.activateConfig is deprecated

### LINKED ISSUE #66: Package.activateConfig is deprecated.
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
Package.activateConfig (/opt/atom/resources/app.asar/src/package.js:265:11)
PackageDetailView.activate (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
PackageDetailView.initialize (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:146:12)
PackageDetailView.View (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
new PackageDetailView (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:38:54)
<unknown> (/opt/atom/resources/app.asar/node_modules/settings-view/lib/settings-view.js:256:22)
```

### PR DESCRIPTION
**Pull request by andywenk**
This PR will fix the deprecation warning Package.activateConfig is deprecated

* add new version and require atom >= 1.0.0
* change the way the config is set
* Update .travis.yml
* add sudo required
* add config schema
* fix naming bug

This closes #66

### CODE REVIEW

**Comment by andywenk** [comment]
I have added travis ci. You might want to do this also in your repo

**Comment by matugm** [comment]
Thanks for your contribution! Not sure if we want to add travis right now, would it be too much work to split that into a separate PR?

**Comment by andywenk** [comment]
erm ... does it hurt just to leave it inside? I mean it's just the .travis.yml file - if you really don't want it I will simply remove it in this PR

**Comment by andywenk** [comment]
the .travis.yml file is now in .gitignore. Feel free to add a .travis.yml file if you wish and remove the entry in .gitignore

**Comment by andywenk** [comment]
just realised, that the version in atom is 0.3.2, I made a 0.3.3 but the releases here do not have these versions. Imho this should be fixed also ... simply create a tag 0.3.3 before you make a new release ;-)

**Comment by matugm** [comment]
The thing with the version is that the tool used to push a package to the atom repo (apm) automatically increases the version number + tag with that version.

**Comment by andywenk** [comment]
ah ok I understand. Funny ;-). Anything left to do here for me with the PR?

**Pull request merged**
